include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - pigeons/**  # Pigeon input files are processed by code generator
    - example/**  # Example app may have different dependencies

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
